"""add dob, fname, lname

Revision ID: 0193981d4bb8
Revises: 2dd3bc165846
Create Date: 2024-11-10 11:47:19.590758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0193981d4bb8'
down_revision: Union[str, None] = '2dd3bc165846'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('students', sa.Column('lastname', sa.String(length=120), nullable=False))
    op.add_column('students', sa.Column('dob', sa.Date(), nullable=True))
    op.drop_column('students', 'fullname')
    op.add_column('teachers', sa.Column('first_name', sa.String(length=120), nullable=False))
    op.add_column('teachers', sa.Column('lastname', sa.String(length=120), nullable=False))
    op.add_column('teachers', sa.Column('dob', sa.Date(), nullable=True))
    op.drop_column('teachers', 'fullname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('fullname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'dob')
    op.drop_column('teachers', 'lastname')
    op.drop_column('teachers', 'first_name')
    op.add_column('students', sa.Column('fullname', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('students', 'dob')
    op.drop_column('students', 'lastname')
    op.drop_column('students', 'first_name')
    # ### end Alembic commands ###
