"""add dob, fname, lname

Revision ID: 1e4c75618db0
Revises: 15185e001e94
Create Date: 2024-11-10 11:54:50.929120

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1e4c75618db0"
down_revision: Union[str, None] = "15185e001e94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "students", sa.Column("last_name", sa.String(length=120), nullable=True)
    )
    op.drop_column("students", "lastname")
    op.add_column(
        "teachers", sa.Column("last_name", sa.String(length=120), nullable=True)
    )
    op.drop_column("teachers", "lastname")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "teachers",
        sa.Column(
            "lastname", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("teachers", "last_name")
    op.add_column(
        "students",
        sa.Column(
            "lastname", sa.VARCHAR(length=120), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("students", "last_name")
    # ### end Alembic commands ###
