"""add contacts

Revision ID: 05bdc3f4f22e
Revises: 28d28adc62a1
Create Date: 2024-11-16 18:55:19.843586

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "05bdc3f4f22e"
down_revision: Union[str, None] = "28d28adc62a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
