"""add PersonType

Revision ID: b65ed992943c
Revises: bcb9eecc1a1a
Create Date: 2024-11-26 09:24:45.485155

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b65ed992943c"
down_revision: Union[str, None] = "bcb9eecc1a1a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE persontype AS ENUM ('student', 'teacher')")
    op.add_column(
        "contacts",
        sa.Column(
            "person_types",
            sa.Enum("student", "teacher", name="persontype"),
            nullable=True,
            default="student",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("contacts", "person_types")
    op.execute("DROP TYPE persontype)")
    # ### end Alembic commands ###
