"""contacts fix

Revision ID: 7d5dfa3b1d88
Revises: ff1b6d03d33f
Create Date: 2024-12-02 19:55:40.995969

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7d5dfa3b1d88"
down_revision: Union[str, None] = "ff1b6d03d33f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column(
            "person_type",
            sa.Enum("teacher", "student", name="persontype"),
            nullable=True,
        ),
    )
    op.drop_column("contacts", "person_types")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column(
            "person_types",
            postgresql.ENUM("student", "teacher", name="persontype"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("contacts", "person_type")
    # ### end Alembic commands ###
