"""initial

Revision ID: 509629b84bfe
Revises: 94bb90b3023d
Create Date: 2024-11-07 14:20:19.816108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '509629b84bfe'
down_revision: Union[str, None] = '94bb90b3023d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('teachers', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teachers', 'is_active')
    op.drop_column('students', 'is_active')
    # ### end Alembic commands ###
