"""add dob, fname, lname

Revision ID: f9e9c8525920
Revises: 0193981d4bb8
Create Date: 2024-11-10 11:51:02.483830

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f9e9c8525920"
down_revision: Union[str, None] = "0193981d4bb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "first_name", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "students", "lastname", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "teachers", "first_name", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    op.alter_column(
        "teachers", "lastname", existing_type=sa.VARCHAR(length=120), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "teachers", "lastname", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "teachers", "first_name", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "students", "lastname", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    op.alter_column(
        "students", "first_name", existing_type=sa.VARCHAR(length=120), nullable=False
    )
    # ### end Alembic commands ###
